include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 3000

build-review:
  # These variables are available only for review env and are merged with the general variables defined above.
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    DOCKER_BUILD_ARG_SASS_PATH: "./src/assets/styles"
    DOCKER_BUILD_ARG_REACT_APP_GRAPHQL_BASE_URL: "https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql"
    DOCKER_BUILD_ARG_REACT_APP_SSR_PORT: 3000
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
    DOCKER_BUILD_ARG_SASS_PATH: "./src/assets/styles"
    DOCKER_BUILD_ARG_REACT_APP_GRAPHQL_BASE_URL: "https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql"
    DOCKER_BUILD_ARG_REACT_APP_SSR_PORT: 3000
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-production"
    DOCKER_BUILD_ARG_SASS_PATH: "./src/assets/styles"
    DOCKER_BUILD_ARG_REACT_APP_GRAPHQL_BASE_URL: "https://tapahtumat-proxy.prod.kuva.hel.ninja/proxy/graphql"
    DOCKER_BUILD_ARG_REACT_APP_SSR_PORT: 3000
  only:
    refs:
      - master
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    POSTGRES_ENABLED: 0


staging:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
  only:
    refs:
      - develop

production:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
