version: "3.7"
services:
  events-helsinki-client:
    build:
      context: client
      dockerfile: Dockerfile-client
      args:
        - SASS_PATH=${SASS_PATH}
        - REACT_APP_GRAPHQL_BASE_URL=${REACT_APP_GRAPHQL_BASE_URL}
        - REACT_APP_SSR_PORT=${REACT_APP_SSR_PORT}
    image: events-helsinki-client
    ports:
      - "${REACT_APP_SSR_PORT}:${REACT_APP_SSR_PORT}"
    
  events-helsinki-graphql-proxy:
    build:
      context: graphql-proxy
      dockerfile: Dockerfile-proxy
      args:
        - GRAPHQL_PROXY_DEBUG=${GRAPHQL_PROXY_DEBUG}
        - GRAPHQL_PROXY_PORT=${GRAPHQL_PROXY_PORT}
        - GRAPHQL_PROXY_ENGINE_API_KEY=${GRAPHQL_PROXY_ENGINE_API_KEY}
        - GRAPHQL_PROXY_LINKED_COURSES_API_BASE_URL=${GRAPHQL_PROXY_LINKED_COURSES_API_BASE_URL}
        - GRAPHQL_PROXY_LINKED_EVENTS_API_BASE_URL=${GRAPHQL_PROXY_LINKED_EVENTS_API_BASE_URL}
    image: events-helsinki-graphql-proxy
    ports: 
      - "${GRAPHQL_PROXY_PORT}:${GRAPHQL_PROXY_PORT}"
