version: '3.7'
services:
  events-helsinki-client:
    # https://github.com/facebook/create-react-app/issues/8688
    # The stdin_open setting circumvents the above issue. Without this
    # setting, docker-compose up won't work as expected.
    stdin_open: true
    container_name: events-helsinki-ui
    image: events-helsinki-client
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - '3001:3001'
