version: "3.7"
services:
  events-helsinki-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SASS_PATH=${SASS_PATH}
        - REACT_APP_GRAPHQL_BASE_URL=${REACT_APP_GRAPHQL_BASE_URL}
        - REACT_APP_SSR_PORT=${REACT_APP_SSR_PORT}
        - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
        - REACT_APP_SENTRY_ENVIRONMENT=${REACT_APP_SENTRY_ENVIRONMENT}
    image: events-helsinki-client
    ports:
      - "${REACT_APP_SSR_PORT}:${REACT_APP_SSR_PORT}"
