name: k6 Load Tests
on:
   push:
      branches: [k6-poc]
jobs:
  k6_load_test:
    name: k6 Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run k6 tests
        uses: k6io/action@v0.1
        with:
          filename: k6LoadTests.js
