name: k6 Load Tests
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  k6_load_test:
    name: k6 Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run k6 tests
        uses: k6io/action@v0.1
        with:
          filename: k6LoadTests.js
      - name: k6 Load Tests notifications
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: AlertManager
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || (job.status == 'failure' && 'danger' || 'warning') }}
          SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_48.png
          SLACK_TITLE: K6 load tests job result is ${{ job.status }}.
          SLACK_MESSAGE: K6 load tests job result is ${{ job.status }}.
        if: always()