name: k6 Load Tests
on:
  push:
    branches: [k6-poc]
  schedule:
  # Mon-Fri 5AM Finnish time (UTC+3)
  - cron: '0 2 * * 1-5'
jobs:
  k6_load_test:
    name: k6 Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run k6 tests
        uses: k6io/action@v0.1
        with:
          filename: k6LoadTests.js
      - name: k6 Load Tests failed notifications
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: k6 Load tests has failed
        if: failure()