name: k6 Load Tests
on:
  schedule:
  # Mon-Fri 5AM Finnish time (UTC+3)
  - cron: '0 8 * * 1-5'
jobs:
  k6_load_test:
    name: k6 Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run k6 tests
        uses: k6io/action@v0.1
        with:
          filename: k6LoadTests.js
