name: Build & Staging & Acceptance tests for Release 1.0
on:
  push:
    branches:
      - master

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  SERVICE_PORT: 3001
  K8S_REQUEST_CPU: 60m
  K8S_REQUEST_RAM: 150Mi
  K8S_LIMIT_CPU: 1000m
  K8S_LIMIT_RAM: 200Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        service: [ "1.0", "2.0" ]
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging-${{ matrix.service == '1.0' && '1' || '2'}}
          DOCKER_BUILD_ARG_PUBLIC_URL: https://${{matrix.service == '1.0' && 'https://tapahtumat.test.kuva.hel.ninja' || 'https://latest-events.test.kuva.hel.ninja'}}
          DOCKER_BUILD_ARG_SASS_PATH: './src/assets/styles'
          DOCKER_BUILD_ARG_REACT_APP_GRAPHQL_BASE_URL: 'https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql'
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'test'
          DOCKER_BUILD_ARG_REACT_APP_CMS_URL: 'https://cms.test.kuva.hel.ninja/api'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_EVENTS_URL: 'https://api.hel.fi/linkedevents/v1'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_COURSES_URL: 'https://api.hel.fi/linkedcourses/v1'
          DOCKER_BUILD_ARG_REACT_APP_IMAGE_PROXY_URL: 'https://images.weserv.nl/?w=1024&url='
          DOCKER_BUILD_ARG_REACT_APP_GENERATE_SITEMAP: 'false'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_URL_BASE: 'https://analytics.hel.ninja/'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SITE_ID: 64
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_ENABLED: 'false'
          DOCKER_BUILD_ARG_REACT_APP_GTM_AUTH: ${{ secrets.GH_QA_GTM_AUTH }}
          DOCKER_BUILD_ARG_REACT_APP_GTM_ID: ${{ secrets.GH_QA_GTM_ID }}
          DOCKER_BUILD_ARG_REACT_APP_GTM_PREVIEW: ${{ secrets.GH_QA_GTM_PREVIEW }}
          # Feature flags
          DOCKER_BUILD_ARG_REACT_APP_SHOW_SIMILAR_EVENTS: 'false'
          DOCKER_BUILD_ARG_EVENTS_HELSINKI_2: ${{ matrix.service == '1.0' && 'false' || 'true' }}
  staging:
    strategy:
      fail-fast: false
      matrix:
        service: [ "1.0", "2.0" ]
    runs-on: ubuntu-latest
    needs: build
    name: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging-${{ matrix.service }}
          PROJECT_NAME: ${{ matrix.service }}
  acceptance-tests:
    runs-on: windows-latest
    needs: staging
    name: Acceptance tests for Staging ${{ matrix.service}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile --check-files --production=false
      - name: Run TestCafe tests
        run: yarn browser-test:ci
        env:
          BROWSER_TESTS_LOCAL_ENV_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          REACT_APP_GRAPHQL_BASE_URL: https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql
      - name: Upload screenshots of failed tests
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: screenshots/