name: Build & Staging & Acceptance tests for Release
on:
  push:
    branches: [master]
env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  SERVICE_PORT: 3001
  K8S_REQUEST_CPU: 60m
  K8S_REQUEST_RAM: 150Mi
  K8S_LIMIT_CPU: 1000m
  K8S_LIMIT_RAM: 200Mi
  K8S_REPLICACOUNT: 2
  REACT_APP_GRAPHQL_BASE_URL: 'https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        service: ['1']
        include:
          - service: '1'
            version: '1.0'
            DOCKER_BUILD_ARG_PUBLIC_URL: https://tapahtumat.test.kuva.hel.ninja
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging-${{ matrix.service }}
          DOCKER_BUILD_ARG_PUBLIC_URL: ${{matrix.DOCKER_BUILD_ARG_PUBLIC_URL}}
          DOCKER_BUILD_ARG_SASS_PATH: './src/assets/styles'
          DOCKER_BUILD_ARG_REACT_APP_GRAPHQL_BASE_URL: ${{ env.REACT_APP_GRAPHQL_BASE_URL }}
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'test'
          DOCKER_BUILD_ARG_REACT_APP_CMS_URL: 'https://cms.test.kuva.hel.ninja/api'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_EVENTS_URL: 'https://api.hel.fi/linkedevents/v1'
          DOCKER_BUILD_ARG_REACT_APP_IMAGE_PROXY_URL: 'https://images.weserv.nl/?w=1024&url='
          DOCKER_BUILD_ARG_REACT_APP_GENERATE_SITEMAP: 'false'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_URL_BASE: '//webanalytics.digiaiiris.com/js/'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SITE_ID: 708
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_ENABLED: 'false'
          DOCKER_BUILD_ARG_REACT_APP_GTM_AUTH: ${{ secrets.GH_QA_GTM_AUTH }}
          DOCKER_BUILD_ARG_REACT_APP_GTM_ID: ${{ secrets.GH_QA_GTM_ID }}
          DOCKER_BUILD_ARG_REACT_APP_GTM_PREVIEW: ${{ secrets.GH_QA_GTM_PREVIEW }}
          # Feature flags
          DOCKER_BUILD_ARG_REACT_APP_SHOW_SIMILAR_EVENTS: 'false'
  staging:
    strategy:
      fail-fast: false
      matrix:
        service: ['1']
        include:
          - service: '1'
            version: '1.0'
            DOCKER_BUILD_ARG_PUBLIC_URL: https://tapahtumat.test.kuva.hel.ninja
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to ${{matrix.DOCKER_BUILD_ARG_PUBLIC_URL}} + Acceptance tests
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2
      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: ${{matrix.DOCKER_BUILD_ARG_PUBLIC_URL}}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging-${{ matrix.service }}
          PROJECT_NAME: ${{ matrix.service }}
      - name: staging deploy failure notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: DeployManager
          SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_48.png
          SLACK_TITLE: Deploying to ${{ matrix.DOCKER_BUILD_ARG_PUBLIC_URL }} has *FAILED!*
          SLACK_MESSAGE: Deploying to ${{ matrix.DOCKER_BUILD_ARG_PUBLIC_URL }} has *FAILED!*
          SLACK_CHANNEL: pomodori-alerts
        if: failure()
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile --check-files --production=false
      - name: Run TestCafe tests For ${{matrix.DOCKER_BUILD_ARG_PUBLIC_URL}}
        id: testcafe
        run: yarn browser-test:ci
        env:
          BROWSER_TESTS_LOCAL_ENV_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          GITHUB_WORKFLOW_NAME: ${{  github.workflow }}
          GITHUB_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TESTCAFE_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          TESTCAFE_SLACK_CHANNEL: '#pomodori-alerts'
          TESTCAFE_SLACK_USERNAME: TestCafé
      - name: Upload results
        run: |
          zip -r report.zip report/ > no_output 2>&1
          curl -s -H "Content-Type: application/zip" -H "Authorization: Bearer ${{secrets.NETLIFY_AUTH_TOKEN}}" --data-binary "@report.zip" https://api.netlify.com/api/v1/sites > response.json
          echo "REPORT_URL=$(cat response.json|python -c "import sys, json; print('https://' + json.load(sys.stdin)['subdomain'] + '.netlify.com')")" >> $GITHUB_ENV
        if: always() && steps.testcafe.outcome == 'failure'
      - name: link screenshots url to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: TestCafé
          SLACK_TITLE: ${{ github.workflow }} have *FAILED*!
          SLACK_MESSAGE: '*Check the testcafe report here for ${{matrix.DOCKER_BUILD_ARG_PUBLIC_URL}}: ${{env.REPORT_URL}}*'
          SLACK_CHANNEL: pomodori-alerts
        if: always() && steps.testcafe.outcome == 'failure'
      - name: Upload screenshots and videos of failed tests to artifact for ${{matrix.DOCKER_BUILD_ARG_PUBLIC_URL}}
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report/
        if: always() && steps.testcafe.outcome == 'failure'
